### ISSUE TITLE
[BUG] - Albedo doesn't work

### ISSUE THREAD

**Issue by duhdire** [Aeroluna/BSAudioLink#2]
**Description**
The albedo does not work with the shaders in-game, but shows up in Unity Editor. Only the emission works.

**Reproduction steps**

1.  Create a new material
2. Assign it with any AudioLink/Surface material
3. Assign albedo, normal, and emission maps, with emission and default settings.
4. Load into modded beatsaber version 1.29.0, the mod shows up in mod assistant so **I think** it is supported.

**Screenshots**
![image](https://github.com/Aeroluna/BSAudioLink/assets/138962419/4de50e2a-aa62-423e-b077-46b56e69e312)
![image](https://github.com/Aeroluna/BSAudioLink/assets/138962419/cd760fa3-adec-4660-b00a-3c8ff7b69094)

**Comment by duhdire** [comment]
Ermm these too :/

![image](https://github.com/Aeroluna/BSAudioLink/assets/138962419/d088c1f6-c0a5-430e-af5c-3f5409ec638c)

It is as simple as opening the relevant scripts to get rid of `using UnityEngine.UI;`, but eh.

**Comment by Aeroluna** [comment]
This is an issue with the shaders being used, not with the mod. Beat Saber compliant versions of the surface shaders are not currently available.
